### ISSUE TITLE
Setup the `defenseunicorns/pkg` library repo

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/pkg#36]
### Describe what should be investigated or refactored
We need to setup the `defenseunicorns/pkg` repo in order to have a home for all of the different libraries that we are seeking to make reuseable from Zarf.  This includes:

- [ ] creating a README.md
- [x] creating an Apache2.0 LICENSE file
- [x] creating a CONTRIBUTING.md
- [x] creating a SECURITY.md
- [x] creating a CODEOWNERS
- [x] setting up OpenSSF scorecard
- [x] setting up branch protection
- [x] setting up dependabot (this differs from other repos but is something we have elected to try)
- [x] setting up unit testing workflows for PRs
- [x] setting up a CVE workflow for PRs
- [x] setting up a license workflow for PRs
- [x] setting up a CodeQL workflow for PRs
- [x] setting up U̶D̶S̶ t̶a̶s̶k̶s̶ t̶o̶ r̶u̶n̶  a makefile for CVE / unit tests locally
- [x] defining a release process: (something like https://github.com/defenseunicorns/kubernetes-fluent-client/blob/main/.github/workflows/release.yml)

### Links to any relevant code
https://github.com/defenseunicorns/pkg

### Additional context
This is story 3/4 in an ultimate goal to bring all of Zarf's OCI library into a common library for reuse across projects.

**Comment by justinthelaw** [comment]
Some ideas I gathered (incomplete) are here! https://github.com/justinthelaw/repository-template

**Comment by AustinAbro321** [comment]
We decided against using uds task and opted for make instead. We may look at tasks again in the future, but it is missing some features we want

**Comment by Noxsios** [comment]
Spinning off README.md into its own issue.
