### ISSUE TITLE
ci(commitlint): code scanning alert - Dangerous-Workflow

### ISSUE THREAD

**Issue by Noxsios** [defenseunicorns/pkg#45]
Warning: The suggested title contains the alert rule name. This can expose security information.

Tracking issue for:

- [x] https://github.com/defenseunicorns/pkg/security/code-scanning/1

**Comment by lucasrod16** [comment]
Fixed by https://github.com/defenseunicorns/pkg/commit/c935607ea41a2c55f9fd70f46b2865170867465e
